name: Run API Tests

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pytest requests

    - name: Run tests
      run: |
        pytest tests --junitxml=results/results.xml

    - name: Upload results artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results/results.xml
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Upload results to S3
      run: |
        aws s3 cp results/results.xml s3://cloud-api-automation-tests-bucket/results.xml
